In [1]:
import numpy as np

# Array Creation and Properties

###Create 1D, 2D, and 3D arrays using np.array, np.zeros, np.ones, and np.full.

In [4]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1 ,2, 3],[4 , 5 , 6]] , [[7 ,8,9],[10,11,12]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
a4 = np.zeros(5)
a5 = np.zeros((3,4))
a5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
a5 = np.ones((3,4))
a5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
a7 = np.full((4,5) , 3)
a7

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

###Use np.arange() and np.linspace() to create arrays with evenly spaced values.

In [12]:
a8 = np.arange(2,12)
a8

a9 = np.linspace(-10 , 10 , 5)
a9

array([-10.,  -5.,   0.,   5.,  10.])

###Check array properties: .ndim, .shape, .size, .dtype.

In [13]:
np.ndim(a3)

3

In [14]:
np.shape(a3)

(2, 2, 3)

In [15]:
np.size(a3)

12

In [17]:
a3.dtype

dtype('int64')

#Reshape and Flatten

###Reshape arrays using .reshape() and .flatten().

In [24]:
print(a8)

a8.reshape((2,5))

[ 2  3  4  5  6  7  8  9 10 11]


array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [28]:
print(a7)

a7.flatten()

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

###Practice reshaping arrays between 1D, 2D, and 3D.

In [30]:
print(a2)

a2.reshape(2, 1, 3)

[[1 2 3]
 [4 5 6]]


array([[[1, 2, 3]],

       [[4, 5, 6]]])

#Random Numbers

### Use np.random.randint(), np.random.rand(), np.random.randn(), and np.random.seed()
to create random arrays.

In [40]:
a9 = np.random.randint(0, 10, (3, 4))
a9

array([[5, 5, 6, 1],
       [2, 9, 7, 1],
       [9, 3, 6, 2]])

In [39]:
a9 = np.random.rand(3, 4)
a9

array([[0.72731109, 0.95836788, 0.32467562, 0.49965309],
       [0.81127877, 0.81807148, 0.82027318, 0.51308304],
       [0.56915858, 0.68736857, 0.11303198, 0.92582486]])

In [41]:
# randn Generates random numbers from the standard normal distribution (mean = 0, standard deviation = 1)


np.random.randn(2, 3)     # 2x3 array of normally distributed numbers

array([[-1.08440291, -0.73531742,  0.53164627],
       [-1.00496497, -1.20108448, -0.01600326]])

In [45]:
np.random.seed(123)  # Set seed for reproducibility

# Generate 3 samples from a normal distribution
samples = np.random.randn(3)
print(samples)

[-1.0856306   0.99734545  0.2829785 ]


###Use .mean(), .min(), .max(), .argmin(), .argmax() to summarize data.

In [53]:
print(a2)

np.max(a2)
np.min(a2)
np.mean(a2)
np.argmax(a2) #index of largest number
np.argmin(a2)

[[1 2 3]
 [4 5 6]]


np.int64(0)

#Indexing and Slicing

###Index and slice 1D and 2D arrays.

In [55]:
print(a2)
a2[1][2]  #indexing
a2[: , 0:1]  #slicing

[[1 2 3]
 [4 5 6]]


array([[1],
       [4]])

###Access specific rows, columns, and elements.

In [56]:
a2[0 , :]  #first row
a2[: , 0]  #first column

array([1, 4])

###Use negative indexing.

In [57]:
a2[-1][-1]

np.int64(6)

#Boolean Masking

###Filter values in arrays using conditions

In [68]:
filtered  = a2[a2<3]
filtered

array([1, 2])

###Combine multiple conditions with & (and), | (or).

In [70]:
filtered  = a2[(a2>3) & (a2<7)]
filtered

array([4, 5, 6])

###ount and sum filtered elements.

In [72]:
mask = a2 > 3
count = np.count_nonzero(mask)  # Number of True values
print(count)


np.sum(a2[a2>5])

3


np.int64(6)

#Array Math & Broadcasting

###Perform element-wise operations (+, -, *, /, **, %).

In [62]:
for i in np.nditer(a2):
  print(i+2)

a2 + 2
a2 ** 2

3
4
5
6
7
8


array([[ 1,  4,  9],
       [16, 25, 36]])

###Use broadcasting to add/subtract scalar to/from arrays.

In [66]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
vector = np.array([10, 20, 30])             # Shape (3,)

# Broadcasting: vector becomes [[10,20,30], [10,20,30]]
print(matrix + vector)

[[11 22 33]
 [14 25 36]]


###se np.sum(), np.prod(), np.mean(), etc.

In [65]:
a2.sum()
a2.prod()
a2.mean()

np.float64(3.5)