In [2]:
import numpy as np

#Functions to create arrays

In [11]:
# 1D (Vector)
a = np.array([1,2,3,4,5])
# type(a)
# a
# print(a)

# 2D (matrix)
b= np.array([[1,2,3],[4,5,6]])
# b

# 3D (Tensor)
c = np.array([[[1,2],[3,4],[5,6]]])
c

numpy.ndarray

In [16]:
# float type array

# d = np.array([1,2,3,4],dtype=float)
# d = np.array([1,2,3,4],dtype=bool)
# d = np.array([1,2,3,4],dtype=str)
d = np.array([1,2,'ss','4'])
d

array(['1', '2', 'ss', '4'], dtype='<U21')

In [19]:
# array using range(work exactly as range function)

# e = np.arange(1,11)
# e = np.arange(1,11 , dtype=float)
e = np.arange(1,11 , 2)
e

array([1, 3, 5, 7, 9])

In [34]:
# reshape (to convert the shape of given array)
np.arange(1,11, dtype=float).reshape(2,5)           #convert array to matrix to 2 rows and 5 columns but the number of items must be appropriate

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [35]:
# ones and  (mainly use to initializa arrays)
# np.ones((3,4))
# np.zeros((3,4))
# np.full((4,5) , 3)
# np.random.randint(0, 10,(3, 4))
# np.random.random((3,4))   #generate array/matrix with random numbers b/w 0-1
# np.random.random((3,4,4))
np.random.random((3,4,4))*10

array([[[6.73274378, 3.82162238, 0.6651264 , 2.6031699 ],
        [4.00531613, 0.95796395, 1.41994485, 3.41683668],
        [4.24532141, 8.37092253, 8.24798429, 5.67614106],
        [4.5773035 , 0.03600459, 2.88473731, 2.79700802]],

       [[3.68417945, 8.37054277, 0.42889278, 7.32468852],
        [2.85407081, 3.77421064, 8.05505421, 9.38908855],
        [0.12122333, 0.73838239, 4.84256978, 9.69353063],
        [8.70196118, 3.8319423 , 3.77356521, 7.52564437]],

       [[9.59332782, 0.34494283, 6.95969805, 3.43142982],
        [8.81837922, 4.73848605, 2.3229478 , 5.04487289],
        [1.05028174, 8.81557112, 6.30968121, 3.12377097],
        [0.5270247 , 7.21847905, 4.96520077, 6.77317212]]])

In [180]:
# always produce same random number

np.random.seed(3)  # Set seed for reproducibility

# Generate 3 samples from a normal distribution
samples = np.random.randn(3)
print(samples)

[1.78862847 0.43650985 0.09649747]


In [32]:
# linspace also called linear space (generates points within given range at equal distance)

np.linspace(1,10,5)   #generate 5 points(numbers) b/w 1-10 at equal distance

#identity matric
np.identity(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#Numpy attributes

* every numpyt array is the object of numpy class and so can access many attributes of that class

In [37]:
a1 = np.arange(10)
a2 = np.arange(12 , dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
# ndim (number of dimentions)
# a1.ndim
# a2.ndim
a3.ndim

3

In [ ]:
# a2.flatten()    will make the array flat

In [43]:
# shape (tell shape of array)
# a1.shape
# a2.shape
a3.shape

(2, 2, 2)

In [45]:
# size (give number of items)
a1.size
a3.size

8

In [50]:
# itemsize(tell what size each item takes in memory) it give same size for int and float here but not on other ides
# a1.itemsize
# a3.itemsize
a4 = np.array([1,2,3,4,5] , dtype=str)
a4.itemsize

4

In [52]:
# dtype(tell datatype to items)
# a1.dtype
a2.dtype

dtype('float64')

#Changing DataTypes

In [56]:
#astype

# a3.dtype
a3 = a3.astype(np.int32)
a3.dtype

dtype('int32')

#Array Operations

* we can run many mathamatical operations on our numpy array

In [67]:

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
# a1
# a2

###Scalar Operations

*operating on single array with a single number

In [66]:
#arithmatic

# a1*2
# a1-1
# a1 /2

#relational

# a2 > 15
# a2 == 15



15

### Vector Operations

* when we do operations on more than one numpy array at once

In [70]:
#arithmatic
a1+a2   #both must have same shape
a1-a2   #both must have same shape


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

###Brodcasting

In [ ]:
arr = np.array([1, 2, 3])
print(arr + 5)  # [6, 7, 8] (5 is broadcasted to [5, 5, 5])

matrix = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
vector = np.array([10, 20, 30])             # Shape (3,)

# Broadcasting: vector becomes [[10,20,30], [10,20,30]]
print(matrix + vector)

###Filtration

In [ ]:
filtered  = a2[(a2>3) & (a2<7)]
filtered

In [ ]:
#count nonzero values

mask = a2 > 3
count = np.count_nonzero(mask)  # Number of True values
print(count)

#Array Functions

* we have alot of functions in numpy basically we have function for maximum operations we want to do on aray

In [78]:
a1 = np.random.random((3,3))
a1

array([[0.38269683, 0.03315605, 0.30935913],
       [0.66782515, 0.9215962 , 0.11205827],
       [0.43455631, 0.42063093, 0.62519618]])

In [79]:
# round
a1 = np.round(a1*100)         #round the array
a1

array([[38.,  3., 31.],
       [67., 92., 11.],
       [43., 42., 63.]])

In [88]:
# max/min/sum/product

# np.max(a1)
# np.argmax(a1) #index of largest number
# print(np.min(a1))
# np.min(a1)
# np.prod(a1)
# np.sum(a1)

# now we can do these arithmatic operations on rows and columns
# 0 --> column and 1 -->row
np.max(a1 , axis=0)     #give max of each column
np.sum(a1 , axis=1)     #give sum of each row




array([ 72., 170., 148.])

In [94]:
# statistic operations
# mean/median/std/var

np.mean(a1)
np.median(a1 , axis=1)
np.std(a1 , axis=1)       #standard daviation
np.var(a1)                 #varience

np.float64(685.5555555555555)

In [95]:
# trignometric functions
np.sin(a1)          #apply sin on each item

array([[ 0.29636858,  0.14112001, -0.40403765],
       [-0.85551998, -0.77946607, -0.99999021],
       [-0.83177474, -0.91652155,  0.1673557 ]])

In [98]:
# dot product   (Dot Product of matxices)->simple matxices multiplication
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12 , 24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [101]:
# log and exponent
np.log(a1)
np.exp(a1)


array([[38.,  3., 31.],
       [67., 92., 11.],
       [43., 42., 63.]])

In [110]:
# round/ floor / ceil

# round-> round at nearins int
a5 = np.round(np.random.random((2,3))*10)

# floor -> 3.9 will be 3
# ceil -> 3.9 will be 4
# np.ceil(a5)
np.floor(a5)



array([[4., 8., 9.],
       [1., 2., 9.]])

#Indexing and Slicing

In [116]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [119]:
#Indexing  (fetch one item at a time)

a1[-1]   #get last item
a1[0]     #get first item

a2[2][3]     #OR a2[2,3]    #give row and col

a3[1][0][1] #OR a3[1,0,1]          #give which 2-D array than row and col to that 2-D


np.int64(11)

In [140]:
# Slicing (fetch multiple items at a time)

#1-D
# print(a1[2:5])
a1[2:5]
a1[2:5:2]   #alternate positions

# 2-D
# array[row , col]
a2[0 , :]   #all colums of row 1 (bacically complete row 1)
a2[0:2 , 1:3]

a2[::2 , ::3]   #get all rows ilternate and all colums with jump of two
a2[ : :2 , 1: :2]
a2[1 , ::3]
a2[:2 , 1:]

#3-D array
a3 = np.arange(27).reshape(3,3,3)
a3[0 , 1 , :]
a3[1 , : , 1]
a3[2 , 1: , 1:]
a3[::2 , 0 , ::2]

array([[ 0,  2],
       [18, 20]])

#Iterating

In [146]:
#1-D
a1
# for i in a1:
#   print(i)

#2-D
# nested loop OR we use nditer
for i in np.nditer(a2):
  print(i)

# same goes with 3-D , 4-D ....


0
1
2
3
4
5
6
7
8
9
10
11


#Reshaping

In [156]:
#Reshape(reshape the given array)

#Transpose (give transpose of given array)
np.transpose(a2)      #OR a2.T
a3.T


#Ravel (convert any n-D array to 1-D array)
np.ravel(a2)
np.ravel(a3)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#Stacking

* combining two or more numpy arrays

In [166]:
# horizontal stacking (Arrays must be of same shape same rows and columns)
# a6 = np.arange(20).reshape(5,4)
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5,a4))

# vertical stacking
np.vstack((a4 , a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Splitting

* opposite of stacking
* we can only split in equal parts

In [169]:
#horizontal splitting
np.hsplit(a4 , 2)         #split a4 in 2 equla parts horizontally


#vertical splitting
np.vsplit(a4 , 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]